---
# tasks file for k8s-master
- name: Adding kubeadm to yum repo
  yum_repository:
    name: kube
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing docker, kubeadm & iproute-tc
  package:
    name:
      - docker
      - kubeadm
      - iproute-tc
    state: present

- name: Starting the services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"

- name: Pulling docker images of kubeadm
  command: kubeadm config images pull

- name: Updating docker cgroup
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: Restaring the docker deamon
  service:
    name: docker
    state: restarted

- name: Updating K8s config file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Restarting the services
  command: sysctl --system


- name: Initializing k8s
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

- name: Setting up kubectl
  shell:
    cmd: |
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Deploying funnel
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Token for slave join
  command: kubeadm token create  --print-join-command
  register: token

- name: Cleaning ram from unwanted caches
  shell: echo 3 > /proc/sys/vm/drop_caches
