---
# tasks file for k8s-slave

- name: Adding kubeadm to yum repo
  yum_repository:
    name: kube
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing docker, kubeadm & iproute-tc
  package:
    name:
      - docker
      - kubeadm
      - iproute-tc
    state: present

- name: Starting the services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"

- name: Updating docker cgroup
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: Restaring the docker deamon
  service:
    name: docker
    state: restarted

- name: Updating K8s config file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
- name: RESTARTING SYSCTL ON SN
  command: sysctl --system

- name: Joining 
  command: "{{ hostvars[groups['ec2_master'][0]]['token']['stdout'] }}"

- name: Cleaning ram
  shell: echo 3 > /proc/sys/vm/drop_caches

